# Service definitions for Estonian Ambient Air Quality integration

update_air_quality_data:
  name: Update Air Quality Data
  description: Force an immediate update of air quality data for the specified entity.
  target:
    entity:
      domain: sensor
      integration: estonian_air_quality
  fields:
    entity_id:
      name: Entity
      description: The air quality, pollen, or radiation sensor entity to update.
      required: true
      selector:
        entity:
          domain: sensor
          integration: estonian_air_quality
